### ISSUE TITLE
Remover a validação "Não é permitido adicionar mais de uma Unidade de abertura para a mesma UF"

### ISSUE THREAD

**Issue by tadeubas** [anatelgovbr/mod-sei-peticionamento#11]
Prezados, bom dia!

No nosso Órgão surgiu uma solicitação de abertura de um "Tipos de Processos para Peticionamento de Processo Novo"
em múltiplas unidades, que por se tratar de uma universidade, todas unidades ficam na mesma UF.

Não encontrei opção para desabilitar essa checagem do código abaixo, seria possível não fazer essa validação? Isso gera alguma implicação grave em outras partes do módulo?

https://github.com/anatelgovbr/mod-sei-peticionamento/blob/fc107f9c720e367c4452e61323ae3dd978eca6d0/sei/web/modulos/peticionamento/md_pet_vinc_tp_processo_cadastro.php#L684

Obrigado,
Tadeu

**Comment by neijobson** [comment]
Utilize Cidade distinta para conseguir adicionar múltiplas unidades nesse caso.
Se é no mesmo Órgão, mesma UF e mesma Cidade, então devem segregar mais os Tipos de Processos.

**Comment by tadeubas** [comment]
Bom dia @neijobson 

Não seria possível criar um parâmetro que se ativado pudesse ignorar essa validação?

Obrigado pela rápida consideração da issue!
