### ISSUE TITLE
Problema com Aspas simples (ou duplas?) no campo Orientações do Tipo de Processo para Peticionamento

### ISSUE THREAD

**Issue by nuncanada** [anatelgovbr/mod-sei-peticionamento#2]
Isso causa problema na hora que o usuário externo tenta criar um novo processo daquele tipo, no Chrome volta erro 500, no Firefox ele apresenta apenas um tela branca.

Causa um problema na linha 196 do arquivo md_pet_usu_ext_cadastro_inicializacao.php

Código da linha 191 à 200:

if( $isNivelAcessoPadrao == 'S' && $nivelAcessoPadrao == "1"){
    $objTipoProcDTOHp = clone($objTipoProcDTO);
	$objTipoProcDTOHp->retNumIdHipoteseLegal();
	$objTipoProcDTOHp->retStrNomeHipoteseLegal();
    $objTipoProcDTOHp->retStrBaseLegalHipoteseLegal();
    $objTipoProcDTOHp = $objTipoProcRN->consultar( $objTipoProcDTOHp );
	$idHipoteseLegalPadrao = $objTipoProcDTOHp->getNumIdHipoteseLegal();
    $strHipoteseLegalPadrao = $objTipoProcDTOHp->getStrNomeHipoteseLegal();
    $strHipoteseLegalPadrao .= " (".$objTipoProcDTOHp->getStrBaseLegalHipoteseLegal().")";
}

O problema é quando esse $objTipoProcDTOHp possui preenchida a Observacao com o valor original que possuia uma aspas simples. Agora na hora de fazer a consulta ele não acha mais pois em algum lugar ele duplica a aspas simples para 2 aspas simples.

Banco de dados: Oracle
SEI: 3.1.4
Peticionamento e Intimação Eletrônicos | 3.2.0 | ANATEL (Projeto Colaborativo no Portal do SPB)

**Comment by neijobson** [comment]
Feito teste com aspas duplas e aspas simples no texto de Orientações Gerais do Peticionamento de Processo Novo e sem erro na versão 3.2 e 3.3.

![image](https://user-images.githubusercontent.com/49068090/110217746-954c5780-7e94-11eb-9198-d45bb8d5a318.png)

**Comment by neijobson** [comment]
Feito teste com aspas duplas e aspas simples no texto de Orientações de um Tipo de Processo específico do Peticionamento de Processo Novo e sem erro na versão 3.2 e 3.3.

![image](https://user-images.githubusercontent.com/49068090/110217829-10ae0900-7e95-11eb-998e-812cf419c5eb.png)
