### ISSUE TITLE
Erro ao peticionar processo sigiloso

### ISSUE THREAD

**Issue by danielcoelhocgu** [anatelgovbr/mod-sei-peticionamento#48]
Estamos com o seguinte erro no módulo de peticionamento instalado no SUPER da CGU (Controladoria-Geral da União):

O usuário externo loga no sistema, escolhe fazer peticionamento intercorrente e digita o número de um processo sigiloso. O tipo de processo não possui critério para intercorrente configurado.

Ele preenche o formulário, carrega o arquivo, clica em Peticionar. A janela para assinatura é aberta. Quando ele clica em Assinar, o seguinte erro é exibido:

![image](https://user-images.githubusercontent.com/110624029/219102687-70d134bf-bd87-44f0-b216-cbb2650dfc94.png)

Me parece que ao criar o novo processo de peticionamento, o módulo não copia os credenciados do processo peticionado.

Além do mais, o próprio nível de sigilo também não é copiado do processo peticionado. O SUPER pega do valor sugerido no tipo de processo. Nesse caso o sugerido também é sigiloso, mas ao alterar o sugerido no tipo de processo para restrito, o erro não ocorre mais e o processo de peticionamento é criado como restrito.

Acreditamos que o ideal seria copiar o nível de sigilo e eventualmente os credenciados no processo peticionado ao criar o novo processo de peticionamento intercorrente.

Informações Adicionais:
Versão do módulo: 4.0.3
Versão do SUPER: 4.0.3.5

**Comment by neijobson** [comment]
@danielcoelhocgu 

Publicamos a v4.1.0 do módulo: https://github.com/anatelgovbr/mod-sei-peticionamento/releases

Nela tem, inclusive, novidade que foi demandada pela equipe do SEI da CGU, para "Na Administração de Intercorrente Padrão foi adicionado nova opção para parametrizar forçar ou não que o Peticionamento Intercorrente ocorra em Novo Relacionado quando o processo estiver com nível de acesso global Sigiloso".

O problema acima deve ter sido já resolvido, pois não temos tal erro na Anatel.
De qualquer forma, não damos suporte aos módulos da Anatel no SUPER. Apenas no SEI.
