### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by alexandrecarvalhosilva** [anatelgovbr/mod-sei-peticionamento#5]
To recebendo esse erro direto no log do SEI, alguém sabe oque pode estar ocorrendo?

Erro: Erro cadastrando processo peticionamento do SEI.
Detalhes:

Trilha de Processamento:
exception 'Exception' with message ''Warning: /opt/sei/web/modulos/peticionamento/rn/MdPetProcessoRN.php linha:413.
file_get_contents(/opt/sei/web/../temp/f9a67e69e9a2b4e3d1f4479137977db3): failed to open stream: No such file or directory
'' in /opt/infra/infra_php/Infra.php:196
Stack trace:
#0 [internal function]: infraGerarExcecao(2, 'file_get_conten...', '/opt/sei/web/mo...', 413, Array)
#1 /opt/sei/web/modulos/peticionamento/rn/MdPetProcessoRN.php(413): file_get_contents('/opt/sei/web/.....')
#2 /opt/sei/web/modulos/peticionamento/rn/MdPetProcessoRN.php(763): MdPetProcessoRN->gerarAssinarDocumentoAnexoSeiRN(Object(UnidadeDTO), Array, Object(DocumentoDTO), Object(ProcedimentoDTO), Object(AnexoDTO), Object(MdPetReciboDTO), 'C')
#3 /opt/sei/web/modulos/peticionamento/rn/MdPetProcessoRN.php(245): MdPetProcessoRN->montarArrDocumentos(Array, Object(UnidadeDTO), Object(ProcedimentoDTO), Object(MdPetReciboDTO))
#4 [internal function]: MdPetProcessoRN->gerarProcedimentoControlado(Array)
#5 /opt/infra/infra_php/InfraRN.php(140): call_user_func(Array, Array)
#6 /opt/sei/web/modulos/peticionamento/md_pet_usu_ext_concluir.php(79): InfraRN->__call('gerarProcedimen...', Array)
#7 /opt/sei/web/modulos/peticionamento/md_pet_usu_ext_concluir.php(79): MdPetProcessoRN->gerarProcedimento(Array)
#8 /opt/sei/web/modulos/peticionamento/PeticionamentoIntegracao.php(640): require_once('/opt/sei/web/mo...')
#9 [internal function]: PeticionamentoIntegracao->processarControladorExterno('peticionamento_...')
#10 /opt/sei/web/SeiIntegracao.php(106): call_user_func_array(Array, Array)
#11 /opt/sei/web/controlador_externo.php(74): SeiIntegracao->executar('processarContro...', 'peticionamento_...')
#12 {main}

Navegador: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
GET:
Array
(
[id_tipo_procedimento] => 10479
[acao] => peticionamento_usuario_externo_concluir
[acao_origem] => peticionamento_usuario_externo_concluir
[id_orgao_acesso_externo] => 0
[infra_hash] => 06be481561bee2c0b402732ecfea8bd0
)

POST:
Array
(
[hdnInfraTipoPagina] => 2
[selCargo] => 33
[pwdsenhaSEI] => ********************
[txtEspecificacaoDocPrincipal] => Recadastramento Examinador Credenciado
[nivelAcessoDocPrincipal] => 0
[grauSigiloDocPrincipal] => 0
[hdnListaInteressados] => 100090919
[hdnListaInteressadosIndicados] =>
[hipoteseLegalDocPrincipal] =>
[hipoteseLegalDocEssencial] =>
[hipoteseLegalDocComplementar] =>
[id_tipo_procedimento] => 10479
[hdnDocPrincipal] =>
[hdnDocEssencial] =>
[hdnDocComplementar] => Horácio Alves dos Anjos Júnior - FOP 402.pdf±26/10/2020 10:49:10±459.33 Kb±Anexo FOP 402 - Examinador Credenciado±Público±±nato±±f9a67e69e9a2b4e3d1f4479137977db3±263±FOP 402 - Examinador Credenciado±Nato-digital¥Horácio Alves dos Anjos Júnior - Certificado Conclusão Curso Examinador Credenciado 141.pdf±26/10/2020 10:50:14±115.58 Kb±Anexo Certificado Conclusão Curso Examinador C±Público±±digitalizado± 4±974ee20d1cc0563d97878902b7e5b759±263±Certificado Conclusão Curso Examinador C±Digitalizado¥Horácio Alves dos Anjos Júnior - Comprovante Experiência.pdf±26/10/2020 10:50:31±125.72 Kb±Anexo Comprovante de Experiência±Público±±nato±±75f45f8378cff97c7b011c045eed0ef8±263±Comprovante de Experiência±Nato-digital¥Horácio Alves dos Anjos Júnior - FAP 13 - Examinador Credenciado 141.pdf±26/10/2020 10:56:13±2.09 Mb±Anexo FAP 13 - Examinador Credenciado±Público±±digitalizado± 4±fd3cbc2355d183f7b9890faf80930388±263±FAP 13 - Examinador Credenciado±Digitalizado
[hdnIdUnidadeMultiplaSelecionada] =>
[docPrincipalConteudoHTML] => <p class="Texto_Fundo_Cinza_Maiusculas_Negrito">Orienta&ccedil;&otilde;es para o peticionamento</p>

<p>Esse processo deve ser instru&iacute;do com base na IS 141-004 &ndash; Processos de Certifica&ccedil;&atilde;o de Centros de Instru&ccedil;&atilde;o de Avia&ccedil;&atilde;o Civil &ndash; CIAC, utilizando-se dos Formul&aacute;rios Operacionais disponibilizados no site <a href="https://www.anac.gov.br/assuntos/setor-regulado/empresas/acesso-rapido/modelos-e-formularios" target="_blank">https://www.anac.gov.br/assuntos/setor-regulado/empresas/acesso-rapido/modelos-e-formularios</a></p>

<p>O processo deve ser peticionado por representante legal da entidade ou procurador devidamente constitu&iacute;do.</p>

<p class="Texto_Fundo_Cinza_Maiusculas_Negrito">1. IDENTIFICA&Ccedil;&Atilde;O DO REQUERENTE</p>

<p class="Citacao">&nbsp;</p>

<table border="1" cellpadding="1" cellspacing="1" style="margin-left: auto; margin-right: auto; width: 608px;">
<tbody>
<tr>
<td style="width: 139px;">Nome do Requerente</td>
<td style="width: 456px;">Adler Aviacao Adler Treinamentos e Escola de Aviacao Civil Ltda</td>
</tr>
<tr>
<td style="width: 139px;">CPF / CNPJ</td>
<td style="width: 456px;">3s.568ssasa1/0001-13</td>
</tr>
<tr>
<td style="width: 139px;">E-mail</td>
<td style="width: 456px;">contato@adleraviacao.com.br</td>
</tr>
</tbody>
</table>

<p>&nbsp;</p>

<p>&nbsp;</p>

<div id="idbpfpeogbhifooiagnbbdbffplkfcke">&nbsp;</div>

)

**Comment by neijobson** [comment]
Isso não é erro do Módulo.
Fale com a equipe da Anac a respeito.
