### ISSUE TITLE
Erro ao instalar o Módulo: /sei/scripts/sei_atualizar_versao_modulo_peticionamento.php

### ISSUE THREAD

**Issue by DiegoDiasRoloff** [anatelgovbr/mod-sei-peticionamento#55]
Prezado,
Ao executar o script /opt/sei/scripts/sei_atualizar_versao_modulo_peticionamento.php esta sendo retornado o erro:

Descrição:
Atributo [SinValorMonetario] não recebeu valor.

Trilha de Processamento Original:
\n0 /opt/sei/web/rn/SerieRN.php(837): InfraDTO->__call('getStrSinValorM...', Array)
\n1 /opt/sei/web/rn/SerieRN.php(103): SerieRN-> (Object(SerieDTO), Object(InfraException))
\n2 /opt/infra/infra_php/InfraRN.php(151): SerieRN->cadastrarRN0642Controlado(Object(SerieDTO))

Acredito que seja alguma configuração que deveríamos ter realizado de valor monetário, porem não encontrei essa configuração no SEI, nem no SIP, poderiam me informar qual é o local de configuração.
Além disso acredito que no script, caso não existisse, poderia realizar essa inserção.

Desde já obrigado.

**Comment by DiegoDiasRoloff** [comment]
Após mais alguma verificações encontramos o problema.
Ao realizar o insert na tabela Serie não esta sendo passado o valor para a coluna SinValorMonetario que é NOT NULL.
Acredito que essa coluna tenha sido adicionada em versões mais recentes do SEI, porem essa situação gera este erro para quem esta instalando o módulo pela primeira vez, e possui versões mais recentes do SEI.
Seria necessário criar uma validação no script

**Comment by neijobson** [comment]
@DiegoDiasRoloff 
Estás tentando instalar o módulo em qual versão do SEI?
Ainda não é compatível com o SEI 4.1.

Essa coluna "SinValorMonetario" não existe na tabela "serie" no SEI 4.0.

**Comment by neijobson** [comment]
@DiegoDiasRoloff Estão usando o SEI 4.1?
Não confirmasse.
Qual é o órgão?

Não recomendamos usar no SEI 4.1 mesmo com os ajustes acima, pois não estamos ainda mantendo no SEI 4.1.

**Comment by DiegoDiasRoloff** [comment]
Sim estamos usando a versão 4.1
Prefeitura de Canoas/RS;

Estamos realizando alguns testes em ambiente de Homologação aqui, mas a principio tive apenas esses erro na instalação.
Caso verifique mais alguma coisa te aviso.

**Comment by neijobson** [comment]
Caro @DiegoDiasRoloff 

Os ajustes que você falou que fez no banco de dados foi em cima do core do SEI. Não faça isso!
As tabelas abaixo são do core do SEI e vocês não devem mudar sua estrutura, pois depois não conseguirão atualizar o sistema nas próximas versões:
`ALTER TABLE SEI.TAREFA MODIFY SIN_CONSULTA_PROCESSUAL CHAR(1) DEFAULT 'N' NULL;
ALTER TABLE SEI.PROTOCOLO MODIFY SIN_ELIMINADO CHAR(1) DEFAULT 'N' NULL;
ALTER TABLE SEI.SERIE MODIFY SIN_VALOR_MONETARIO CHAR(1) DEFAULT 'N' NULL;`

Sobre o ajuste abaixo, já cabemos de impactos. E não é somente nesse DTO.
`MdPetDocumentoRN:assinarInternoControlado()
linha 1228
$objProtocoloDTOProcedimento->retStrSinEliminado();`

Insistimos que o melhor é usar por enquanto o SEI 4.0 ou esperar versão oficial do Módulo SEI Peticionamento adaptado para o SEI 4.1.

**Comment by DiegoDiasRoloff** [comment]
Ciente, as alterações no Core foram apenas adicionar o valor default para quando não é passado o parâmetro, mas assim que atualizarmos a versão do posicionamento será revertido.
