### ISSUE TITLE
Erro Excluir Usuário Externo

### ISSUE THREAD

**Issue by jefersongoliveira** [anatelgovbr/mod-sei-peticionamento#58]
Prezado(a), saudações!
A partir do menu _Administração -> Usuários Externos -> Listar_; Na linha onde se encontrar o cadastro do usuário externo, ao clicar no botão "Excluir Usuário Externo" é retornado o seguinte erro: "Método [MdPetIntimacaoRN.existeIntimacaoPorContato] não encontrado."

Versão do SEI: 4.0.10
Versão do módulo "SEI Peticionamento, Intimação e Procuração": 4.0.3

**Comment by neijobson** [comment]
@jefersongoliveira 
Atualize o módulo para v4.1.0

E o SEI para v4.0.12.
