### ISSUE TITLE
Erro no carregamento da imagem /infra_css/imagens/aguarde.gif com arquivo externo

### ISSUE THREAD

**Issue by tadeuufscar** [anatelgovbr/mod-sei-peticionamento#59]
* PETICIONAMENTO: v4.1.0
* SEI: v4.0.12.15

* Erro no carregamento da imagem /infra_css/imagens/aguarde.gif
* Tipo de Processo para Peticionamento Externo (Anexação de Arquivo)

ERRO NA IMAGEM ao lado de **Processando...**:
![peticionamento-aguarde png com erro](https://github.com/anatelgovbr/mod-sei-peticionamento/assets/121962281/4ed00340-b576-44b1-8063-56f18eabaf8c)

TIPO PROCESSO NO PETICIONAMENTO:
![peticionamento-tipo-externo](https://github.com/anatelgovbr/mod-sei-peticionamento/assets/121962281/264c2111-08ac-400d-9899-e38b70557a71)

TIPO PROCESSO NO SEI:
![tipo-processo-peticionamento](https://github.com/anatelgovbr/mod-sei-peticionamento/assets/121962281/e062ff75-0154-4c87-a404-dceaf91f73fb)

**Comment by neijobson** [comment]
@tadeuufscar
Esse não é o SEI 4.0.12 original.

Não damos suporte no SUPER ou nesse SEI que não é o original SEI 4.0.12.

**Comment by tadeuufscar** [comment]
Bom dia @neijobson , obrigado pela resposta! A versão que estamos usando é a disponibilizada aqui https://github.com/pengovbr/sei/releases/tag/4.0.12.15

Ele realmente não é o original SEI 4.0.12, acrescentaram o tema Gov.BR no esquema de cores, e talvez por conta disso (ou outra modificação) acabou dando esse problema.

Já reportei a issue por lá para ver o que me orientam, vou apenas deixar registrado aqui caso outros venham a ter esse problema - https://github.com/pengovbr/sei/issues/339

**Comment by neijobson** [comment]
@tadeuufscar 
Mude de tema e veja se o erro persiste. Avise aqui!

Acho que aproveitaram o SUPER ou aproveitaram o tela do SUPER. Os erros recorrentes em vários módulos que tinham no SUPER estão persistindo nesse outro SEI.

**Comment by tadeubas** [comment]
Oi @neijobson bom dia!

A troca do tema alterou uma parte da tela, mas não o logo do SEI e ficou estranho a barra superior:

No SEI (tema azul celeste):
![image](https://github.com/anatelgovbr/mod-sei-peticionamento/assets/5518496/36dcc799-c5c5-4839-80fe-752b369671ae)

No Peticionamento (tema azul celeste):
![image](https://github.com/anatelgovbr/mod-sei-peticionamento/assets/5518496/aa0d554b-07c0-4344-9c9c-e72a0f1e3d71)

No SEI (tema vermelho):
![image](https://github.com/anatelgovbr/mod-sei-peticionamento/assets/5518496/8f93c834-937b-4330-858a-6a6c5ed1b5e8)

No Peticionamento (tema vermelho):
![image](https://github.com/anatelgovbr/mod-sei-peticionamento/assets/5518496/6225867f-6cfc-426e-9995-2bc831007023)

**Comment by tadeuufscar** [comment]
Oi @neijobson bom dia!

A troca do tema alterou uma parte da tela, mas não o logo do SEI e ficou estranho a barra superior:

No SEI (tema azul celeste):
![image](https://github.com/anatelgovbr/mod-sei-peticionamento/assets/5518496/36dcc799-c5c5-4839-80fe-752b369671ae)

No Peticionamento (tema azul celeste):
![image](https://github.com/anatelgovbr/mod-sei-peticionamento/assets/5518496/aa0d554b-07c0-4344-9c9c-e72a0f1e3d71)

No SEI (tema vermelho):
![image](https://github.com/anatelgovbr/mod-sei-peticionamento/assets/5518496/8f93c834-937b-4330-858a-6a6c5ed1b5e8)

No Peticionamento (tema vermelho):
![image](https://github.com/anatelgovbr/mod-sei-peticionamento/assets/5518496/6225867f-6cfc-426e-9995-2bc831007023)

**Comment by neijobson** [comment]
@tadeuufscar 
Realmente mexeram até no tema original do SEI, pois não está a logo correta no Acesso Externo do SEI. Vide print abaixo.
De qualquer forma, os problemas foram corrigidos e funcionou tudo no Pesquisa e no Peticionamento?

Meu e-mail está aqui no README: https://github.com/anatelgovbr/mod-sei-peticionamento#readme
Me envia um e-mail para conferir mais detalhes diretamente contigo.

![image](https://github.com/anatelgovbr/mod-sei-peticionamento/assets/49068090/04abf59f-9c72-4d43-9595-5c65f1991315)

**Comment by tadeuufscar** [comment]
@neijobson Enviei um email! 

Fiz os testes aqui de busca e talz, fora esses problemas na interface / logo do SEI, não vi outros problemas, segue imagem dos temas disponíveis, veja que o padrão deles é esse Gov.BR (branco)

![image](https://github.com/anatelgovbr/mod-sei-peticionamento/assets/121962281/814e5ab7-e262-4440-bcb1-0889cc38078f)

**Comment by caduvieira** [comment]
> * Erro no carregamento da imagem /infra_css/imagens/aguarde.gif

Essa imagem existe no SEI 4.0.12.15
https://github.com/pengovbr/sei/tree/4.0.12.15/src/infra/infra_css/imagens

**Comment by caduvieira** [comment]
> Oi @neijobson bom dia!
> 
> A troca do tema alterou uma parte da tela, mas não o logo do SEI e ficou estranho a barra superior:
> 
> No SEI (tema azul celeste): ![image](https://user-images.githubusercontent.com/5518496/279334589-36dcc799-c5c5-4839-80fe-752b369671ae.png)
> 
> No Peticionamento (tema azul celeste): ![image](https://user-images.githubusercontent.com/5518496/279334748-aa0d554b-07c0-4344-9c9c-e72a0f1e3d71.png)
> 
> No SEI (tema vermelho): ![image](https://user-images.githubusercontent.com/5518496/279335108-8f93c834-937b-4330-858a-6a6c5ed1b5e8.png)
> 
> No Peticionamento (tema vermelho): ![image](https://user-images.githubusercontent.com/5518496/279335215-6225867f-6cfc-426e-9995-2bc831007023.png)

Essa simulação creio que não aconteça para o usuário externo comum sem acesso a um usuário interno.


https://github.com/anatelgovbr/mod-sei-peticionamento/assets/3831408/43d533cb-799f-4aca-b7bf-0fb582c25464



Não consegui simular a troca de tema sendo um usuário externo sem acesso a um usuário interno.

**Comment by caduvieira** [comment]
> @tadeuufscar Mude de tema e veja se o erro persiste. Avise aqui!
> 
> Acho que aproveitaram o SUPER ou aproveitaram o tela do SUPER. Os erros recorrentes em vários módulos que tinham no SUPER estão persistindo nesse outro SEI.

Caso ainda haja outros erros de módulos da compatibilidade com o SEI distribuído com o MGI pode marcar para verificarmos. Obrigado

**Comment by neijobson** [comment]
@caduvieira Tem razão. Testei aqui e o Acesso Externo do SEI não tem escolha de tema.

Mas se o usuário estiver logado no mesmo micro/navegador no SEI Interno e Externo, tem uma confusão de sessões e aí o tema escolhido internamente muda o tema externo. Mas aí é um comportamento do core do SEI que não temos o que fazer por meio do Módulo de Peticionamento.
