### ISSUE TITLE
Incompatibilidade com versão 4.1.1

### ISSUE THREAD

**Issue by raphaeljpb** [anatelgovbr/mod-sei-peticionamento#62]
Verifiquei esses pequenos ajustes ao atualizar o módulo na versão 4.1.1 do SEI.

1. No arquivo MdPetIntUsuarioRN.php, excluir linha 77 ($objUsuarioDTO->setStrSinAcessibilidade(MdPetIntUsuarioRN::$NAO);).
2. No arquivo MdPetDocumentoRN.php, adicionar código $objProtocoloDTOProcedimento->retStrSinEliminado(); após a linha 1227.
3. No arquivo sei_atualizar_versao_modulo_peticionamento.php, fazer os ajustes abaixo:

Adicionar o código $serieDTO->setStrSinValorMonetario('N'); após a linha 721.
Adicionar o código $tarefaDTO1->setStrSinConsultaProcessual('S'); após a linha 1211.
Adicionar o código $tarefaDTO2->setStrSinConsultaProcessual('S'); após a linha 1230.
Adicionar o código $tarefaDTO3->setStrSinConsultaProcessual('S'); após a linha 1250.
Adicionar o código $tarefaDTO4->setStrSinConsultaProcessual('S'); após a linha 1270.
Adicionar o código $serieDTO->setStrSinValorMonetario('N'); após a linha 1374.
Adicionar o código $serieDTO->setStrSinValorMonetario('N'); após a linha 3120.
Adicionar o código $serieDTO->setStrSinValorMonetario('N'); após a linha 3332.
Adicionar o código $serieDTO->setStrSinValorMonetario('N'); após a linha 3545.
Adicionar o código $serieDTO->setStrSinValorMonetario('N'); após a linha 3756.
Adicionar o código $serieDTO->setStrSinValorMonetario('N'); após a linha 3967.
Adicionar o código $serieDTO->setStrSinValorMonetario('N'); após a linha 4178.
Adicionar o código $serieDTO->setStrSinValorMonetario('N'); após a linha 4389.
Adicionar o código $serieDTO->setStrSinValorMonetario('N'); após a linha 4508.

**Comment by neijobson** [comment]
@raphaeljpb 
Ainda vamos liberar versão adaptada para o SEI 4.1.1.
Não antecipe o uso do módulo no SEI 4.1.1!

**Comment by gsdiniz** [comment]
É possível instalar a versão atual no SEI 4.1.0?

**Comment by neijobson** [comment]
@gsdiniz Conforme dito acima, não é compatível.
Devem esperar. Em duas semanas liberaremos a versão que será compatível com o SEI 4.1.

**Comment by neijobson** [comment]
@raphaeljpb 
Lançamos tem algumas semanas a v4.2.0 compatível com o SEI 4.1.2: https://github.com/anatelgovbr/mod-sei-peticionamento/releases

**Comment by gsdiniz** [comment]
Essa versão suporta compatibilidade com a versão a versão SEI 4.1.1?

**Comment by neijobson** [comment]
@gsdiniz 
A v4.2.0 do módulo é compatível com o SEI 4.1.2.

![image](https://github.com/anatelgovbr/mod-sei-peticionamento/assets/49068090/8fdf7f46-9e66-4020-b02d-49eeb25b27e0)

**Comment by gsdiniz** [comment]
@neijobson 

Baseado no documento da versão 4.1.2, 
[SEI-v4.1.2.pdf](https://github.com/anatelgovbr/mod-sei-peticionamento/files/15012172/SEI-v4.1.2.pdf)

que indica correções de erros na aplicação, ocorreram testes na versão 4.1.1 ou os erros corrigidos na versão 4.1.1 para a versão 4.1.2 são obrigatórios para o funcionamento do peticionamento?

**Comment by neijobson** [comment]
@gsdiniz a versão mínima do Peticionamento 4.2.0 para o SEI é o SEI 4.1.2
Não vai conseguir instalar em outro

A atualização do SEI 4.1.1 para 4.1.2 é apenas de código.
Mas o módulo precisa que esteja no SEI 4.1.2.

Siga o que consta no README e nos Releases Notes da versão.
