### ISSUE TITLE
Suporte a Postgres?

### ISSUE THREAD

**Issue by fabiorauber** [anatelgovbr/mod-sei-peticionamento#66]
Olá! Estava tentando instalar o módulo de peticionamento no SEI versão 4.0.9, mas percebi que o banco de dados Postgres não é suportado, apenas MySQL, Oracle e MS SQL:

https://github.com/anatelgovbr/mod-sei-peticionamento/blob/50ffa51e90c727d5088c7721d4f0e08f2316ef0a/sei/scripts/sei_atualizar_versao_modulo_peticionamento.php#L96

Dito isto, pergunto aos desenvolvedores: há alguma limitação não contornável para se utilizar o módulo com o Postgres, ou previsão de suporte a ele no futuro?

Obrigado!

**Comment by neijobson** [comment]
@fabiorauber ainda não, pois a Seges/MGI não forneceu ainda o ambiente do SEI Localhost para desenvolvimento nesse tipo de SGBD.

**Comment by caduvieira** [comment]
Sim tem.
https://github.com/anatelgovbr/mod-sei-peticionamento/issues/67#issuecomment-2183376215
