### ISSUE TITLE
Esse módulo tem suporte ao Banco de Dados PostgreSQL?

### ISSUE THREAD

**Issue by nettoinfo** [anatelgovbr/mod-sei-peticionamento#67]
Olá!
Gostaria de saber se esse módulo tem suporte ao PostgreSQL, pois nós adotamos esse banco de dados.
Caso não tenha, existe algum versionamento que terá?!
Grato!
José Ferreira Neto
Depto. TI

**Comment by neijobson** [comment]
@fabiorauber ainda não, pois a Seges/MGI não forneceu ainda o ambiente do SEI Localhost para desenvolvimento nesse tipo de SGBD.

**Comment by caduvieira** [comment]
Sim existe o banco de referência no postgres para o 4.0 e 4.1
https://github.com/spbgovbr/sei-db-ref-executivo/tree/master/postgresql

O SEI localhost pode subir sim com o 
`$ make config base=postgresql && make up`

@nettoinfo para seu conhecimento.
