### ISSUE TITLE
Versão 4.1.1 - Não é possível configurar a funcionalidade consultar dados CNPJ sem integração

### ISSUE THREAD

**Issue by brulere** [anatelgovbr/mod-sei-peticionamento#68]
Prezados,

Não está sendo possível configurar a funcionalidade de consultar dados CNPJ Receita Federal sem a integração, conforme screenshot abaixo:
![image](https://github.com/anatelgovbr/mod-sei-peticionamento/assets/163012561/f1c92d41-73dc-4289-b7c3-3fd2fc0bdec9)

Segue também o log completo em anexo.
[log procuracao cnpj.txt](https://github.com/anatelgovbr/mod-sei-peticionamento/files/14560396/log.procuracao.cnpj.txt)

Exception: 'Warning: /opt/infra/infra_php/InfraOracle.php linha:634.
oci_execute(): ORA-01400: cannot insert NULL into (&quot;BD_SEI40&quot;.&quot;MD_PET_ADM_INTEGRACAO&quot;.&quot;ENDERECO_WSDL&quot;)
' in /opt/infra/infra_php/Infra.php:246

**Comment by neijobson** [comment]
@brulere 
Se estiverem na versão 4.0.12, atualizem para a v4.1.1 do Módulo: https://github.com/anatelgovbr/mod-sei-peticionamento/releases

Não conseguimos reproduzir o erro acima. Pode ser também algum problema local que precisam revisar.

**Comment by brulere** [comment]
@neijobson e-mail enviado.
