### ISSUE TITLE
Script de atualização para versão 4.1.1 do peticionamento não atualiza corretamente o número da versão

### ISSUE THREAD

**Issue by mauriciocoelho** [anatelgovbr/mod-sei-peticionamento#69]
Foi identificado no script de atualização para a versão 4.1.1 do peticionamento. Atualmente, o script não inclui a função específica para instalar a versão 4.1.1, oferecendo suporte apenas às versões anteriores. Isso impede a atualização correta para a nova versão. Seria possível revisar e adicionar a função de instalação para a versão 4.1.1 ao script? tanto no SEI quanto no SIP. 
Siga as imagens

![script_sei_1](https://github.com/anatelgovbr/mod-sei-peticionamento/assets/47572310/e21cd423-e843-4547-806a-f6844bae6638)
![script_sei_2](https://github.com/anatelgovbr/mod-sei-peticionamento/assets/47572310/a99b66b5-9f59-476e-b200-a94b54421b34)
![script_sei_3](https://github.com/anatelgovbr/mod-sei-peticionamento/assets/47572310/7cee65d2-4478-46df-8f7b-47faf581001b)
![Modulo_SEI_1](https://github.com/anatelgovbr/mod-sei-peticionamento/assets/47572310/51c8e432-2114-4176-9179-1bd1ee52a865)
![Modulo_SIP_1](https://github.com/anatelgovbr/mod-sei-peticionamento/assets/47572310/932bc225-6288-44c7-8ba1-a796f73e74d7)

**Comment by neijobson** [comment]
Não funcionará no SEI 4.1.1. Apenas a partir do SEI 4.1.2.

E não clonem da master!
Utilizem as Releases/Tags. Versão estável é nelas e não em outro local.
Faça o Pull de Release ou Tag ou peguem como a maioria, manualmente na página de Releases: https://github.com/anatelgovbr/mod-sei-peticionamento/releases

Conferi e o script está correto, na v4.2.0 do módulo e que funciona a partir do SEI 4.1.2.

**Comment by jefersongoliveira** [comment]
Prezado @neijobson, boa tarde.
Acredito que não tenhamos sido claro em expor o problema.
Utilizamos atualmente a versão 4.0.12 do SEI. A versão mais atual do módulo de peticionamento compatível é a 4.1.1. Ao atualizarmos para esta versão o sistema ainda aponta que estamos na versão 4.1.0 conforme a variável VERSAO_MODULO_PETICIONAMENTO. Conforme o @mauriciocoelho informou nas imagens não consta a função instalar411(); e não atualiza corretamente para a versão 4.1.1, fica na versão 4.1.0. Caso não tenhamos sido claro sugiro que possamos reunir em uma call para mostrar o que está acontecendo.

**Comment by neijobson** [comment]
@jefersongoliveira 
Já respondi exatamente sobre esse ponto por e-mail. Converse com o Maurício.

Conforme consta no README do módulo, não controlamos pela variável de banco/script o terceiro dígito.

![image](https://github.com/anatelgovbr/mod-sei-peticionamento/assets/49068090/4b88eeb3-744a-42e7-a33f-22d7f6c91502)
