### ISSUE TITLE
Erros com unidades que possuam acentos e outros caracteres especiais

### ISSUE THREAD

**Issue by s0ckz** [anatelgovbr/mod-sei-peticionamento#7]
No órgão em que trabalho, há unidades com acentos na sigla/descrição. Notei que isso quebrava somente na parte de peticionamento (quando há tipos de peticionamento com múltiplas unidades)...

O problema é que, ao gerar o JSON que contém todas as unidades e é inserido no input `hdnTodasUnidades`, ele fica vazio porque há caracteres inválidos lá... O que fiz para corrigir foi colocar o encoding nas chamadas à função `htmlentities` em https://github.com/anatelgovbr/mod-sei-peticionamento/blob/v3.3.0/sei/web/modulos/peticionamento/md_pet_tipo_processo_cadastro.php#L98

Não sei se é a solução ideal mas resolveu meus problemas.

**Comment by neijobson** [comment]
Esse problema já foi resolvido nas versões mais recentes.
