### ISSUE TITLE
Versão 4.1.2 - Erro ao consultar dados de pessoa jurídica ou atualizar atos constitutivos de pessoa jurídica

### ISSUE THREAD

**Issue by brulere** [anatelgovbr/mod-sei-peticionamento#74]
Na tela do usuário externo, no menu "Responsável Legal de Pessoa Jurídica", caso tenha ocorrido substituição de responsável legal da empresa cadastrada, ao clicar em consultar dados de pessoa jurídica ou tentar atualizar atos constitutivos de pessoa jurídica, a seguinte mensagem de erro aparece:

![Captura de tela 2024-07-18 174651](https://github.com/user-attachments/assets/29198c11-b57c-4e02-a330-2afbbfc8142a)
![Captura de tela 2024-07-18 174755](https://github.com/user-attachments/assets/cd6852af-cc25-4ea4-aecf-3d9a41713d05)

Consulta retornou mais de um registro de MD_PET_VINCULO.

Detalhes:
SELECT DISTINCT md_pet_vinculo.id_md_pet_vinculo AS idmdpetvinculo, contvinc.cnpj AS cnpj, contvinc.nome AS razaosocialnomevinc, contrep.cpf AS cpfcontatorepresentante, contrep.nome AS nomecontatorepresentante, md_pet_vinculo.sin_validado AS sinvalidado, md_pet_vinculo.sin_web_service AS sinwebservice, md_pet_vinculo.id_contato AS idcontato, repr.id_contato AS idcontatorepresentante FROM md_pet_vinculo INNER JOIN contato contvinc ON md_pet_vinculo.id_contato=contvinc.id_contato INNER JOIN (md_pet_vinculo_represent repr INNER JOIN contato contrep ON repr.id_contato=contrep.id_contato) ON md_pet_vinculo.id_md_pet_vinculo=repr.id_md_pet_vinculo AND repr.tipo_representante=:v1 WHERE md_pet_vinculo.id_md_pet_vinculo=:v2

Bind:
v1: L
v2: 4667

Trilha de Processamento:
0 /opt/sei/web/modulos/peticionamento/rn/MdPetVinculoRN.php(135): InfraBD->consultar(Object(MdPetVinculoDTO))
1 /opt/infra/infra_php/InfraRN.php(151): MdPetVinculoRN->consultarConectado(Object(MdPetVinculoDTO))
2 /opt/sei/web/modulos/peticionamento/md_pet_vinc_usu_ext_acoes.php(60): InfraRN->__call('', Array)
3 /opt/sei/web/modulos/peticionamento/md_pet_vinc_usu_ext_cadastro.php(19): require_once('')
4 /opt/sei/web/modulos/peticionamento/PeticionamentoIntegracao.php(893): require_once('')
5 /opt/sei/web/SeiIntegracao.php(121): PeticionamentoIntegracao->processarControladorExterno('')
6 /opt/sei/web/controlador_externo.php(79): SeiIntegracao->executar('', '')
7 {main}

**Comment by neijobson** [comment]
@brulere Pode ter algum problema local com dados duplicados.
Investigar e passar mais dados.

Aqui não conseguimos reproduzir o erro com apena o informado.
O @gabriel9nc consegue corrigir erro se souber a causa. Nesse caso acima, quais dados estão duplicados e porquê?
A correção não está aí, que é consequência. Não pode ter dados duplicados sobre a consulta indicada.
Ache o que está duplicado e investigue porque duplicou.

**Comment by brulere** [comment]
Prezados, não tem segredo. 
Para reproduzir o erro, basta realizar a substituição de um responsável legal de qualquer empresa. 
Aparentemente, quando ocorre a substituição, a tabela md_pet_vinculo devolve os dois contatos de responsável legal na query que estoura o erro.
![tela 1](https://github.com/user-attachments/assets/0d351761-bd5b-4584-b01e-37a8ee624103)
![tela 2](https://github.com/user-attachments/assets/06b18a46-832d-408d-816d-69bb4e24cec9)
![tela 3](https://github.com/user-attachments/assets/e49d8e08-6fa5-4f2d-8ec9-dd4c38268185)

**Comment by brulere** [comment]
@neijobson  e-mail enviado.

**Comment by neijobson** [comment]
@diegoandresantana
Nos reunimos com o pessoal da Anvisa já.

Sobre o retorno de mais de um registro no md_pet_vinculo, o @gabriel9nc  vai subir nova versão logo mais.
Mande por e-mail com mais detalhes e quais erro. Se é somente esse.
Enviar para o e-mail que consta aqui no README do módulo.

**Comment by gabriel9nc** [comment]
Correção na v4.1.3. Atualizar o módulo sobrescrevendo os arquivos para aplicar a correção. À disposição.
