### ISSUE TITLE
Módulo v4.2.1 incompatível com SEI v4.1.3

### ISSUE THREAD

**Issue by ferabreu** [anatelgovbr/mod-sei-peticionamento#75]
Parece que o script de atualização (sip_atualizar_versao_modulo_peticionamento.php) está comparando strings, e não números. Isso impede a instalação da última versão do módulo em uma instância da última versão do SEI (v4.1.3).

No arquivo atualizacao_peticionamento_sip.log:

"00002 - ERRO: VERSÃO DO FRAMEWORK PHP INCOMPATíVEL (VERSÃO ATUAL 2.22.3, SENDO REQUERIDA VERSÃO IGUAL OU SUPERIOR A 2.7.6)"

Versões da infra:

SEI 4.1.2:  `const VERSAO_INFRA = '2.7.6'`
SEI 4.1.3:  `const VERSAO_INFRA = '2.22.3'`

**Comment by neijobson** [comment]
@ferabreu 

O @gabriel9nc  já subiu correção na v4.2.1 do módulo: https://github.com/anatelgovbr/mod-sei-peticionamento/releases
