### ISSUE TITLE
Caracteres inválidos após o peticionamento eletrônico - Tabela com contenteditable=false 

### ISSUE THREAD

**Issue by TiagoPaiva919** [anatelgovbr/mod-sei-peticionamento#78]
Ao criar uma tabela com o contenteditable = false no modelo de documento para ser utilizado como requerimento, quando o usuário vai efetuar o peticionamento eletrônico os caracteres (ã Ã á Á à À ç Ç â Â) em que pese na tela aparecerem normal digitados, após efetuado o peticionamento referidos caracteres são transformados em ? dentro do requrimento no SEI, o mesmo ocorre com células em branco, dentro desta tabela.

Ao utilizarmos o contenteditable = false somente na célula não ocorre o erro dos caracteres acima listado após o peticionamento, porém ao se navegar na tabela utilizando o tab é possível desconfigurar a tabela.

Utilizamos as versões SEI 4.1.2 e Modulo Peticionamento 4.2.2, porém na versão do Módulo 4.2.0 o erro também ocorria.

Segue abaixo imagem com 2 tabelas, sendo a primeira com contenteditable=false e a segunda com contentedtible=true antes e após o peticionamento para visualização, bem como o código html utilizado para montagem das tabelas.

Modelo HTML: [exemplo.txt](https://github.com/user-attachments/files/16948118/exemplo.txt)

Imagem durante o peticionamento: ![pre-peticionamento](https://github.com/user-attachments/assets/5a0dc2e8-b322-4ee8-82d8-febcaca26733)
Imagem após o peticionamento dentro do sei (usuário interno): ![pós-peticionamento](https://github.com/user-attachments/assets/712d38ef-0157-461f-9fc9-e24e648f6a9d)

**Comment by neijobson** [comment]
@TiagoPaiva919 
Isso não é um erro do módulo.
Pode ter um problema geral na instalação do SEI envolvendo encoding correto, conforme o Manual de Instalação do SEI.

De qualquer forma, utilize no SEI 4.1.4 e atualize o código do módulo para a v4.2.3, que são as versões mais recentes.
Também teste no SEI interno, sem usar pelo módulo para conferir se pelo SEI interno o mesmo documento depois de salvo apresenta como os caracteres.

Faça nessa ordem. Deixar na última versão, repetir o teste e testar no SEI interno o mesmo documento.
