### ISSUE TITLE
Erros com unidades com contatos associados

### ISSUE THREAD

**Issue by s0ckz** [anatelgovbr/mod-sei-peticionamento#8]
No meu órgão, há casos de unidades que fazem uso do endereço do contato associado. Com isso, os campos cidade, estado e país (mais especificamente `id_cidade`,  `id_estado`, `id_pais`) ficam vazios, pois eles se encontram no contato de id `id_contato_associado`. Eu tentei fazer uma correção parcial na parte de adicionar todas as unidades em `hdnTodasUnidades`.

O código seria algo como:

```php
        if ($contatoAssociadoDTO != null && $contatoAssociadoDTO->getStrSinEnderecoAssociado() == 'S') {
            $idContatoAssociado = $contatoAssociadoDTO->getNumIdContatoAssociado();
            $contatoAssociadoDTO = new ContatoDTO();
            $contatoAssociadoDTO->retStrSiglaUf();
            $contatoAssociadoDTO->retNumIdContato();
            $contatoAssociadoDTO->retStrNomeCidade();
            $contatoAssociadoDTO->retNumIdCidade();
            $contatoAssociadoDTO->setNumIdContato($idContatoAssociado);
            $contatoAssociadoDTO = $contatoAssociadoRN->consultarRN0324($contatoAssociadoDTO);
        }
```

Esse trecho ficaria após o seguinte trecho: https://github.com/anatelgovbr/mod-sei-peticionamento/blob/v3.3.0/sei/web/modulos/peticionamento/md_pet_tipo_processo_cadastro.php#L112

O sistema chega a salvar corretamente mas, a listagem, após voltar da operação de salvar, volta sem as unidades que possuem contato com endereço associado. Rastreei e vi que é porque o DTO de relacionamento só faz uso do `id_contato`, e não considera o `id_contato_associado`. Como desconheço a API dos projetos SEI/SIP/Infra, fica difícil para eu sugerir uma solução melhor, mas deixo aqui o problema relatado.

**Comment by neijobson** [comment]
Não vamos fazer essa evolução, pois a maioria dos órgãos seguem como boa prática a Unidade ter, cada uma, os seus dados. Assim, não usa Contato Associado para as Unidades.

**Comment by tadeubas** [comment]
Só para constar na UFSCar também fazemos uso do contato associado, são várias unidades em cada Campus e daí todas unidades acabam tendo a mesma cidade, estado e país.

**Comment by neijobson** [comment]
@tadeubas entendido que usam, mas não é adequado por vários motivos.
Cadastrem em cada Unidade os seus dados e vai funcionar tudo ok.
