### ISSUE TITLE
Erro ao rodar sip_atualizar_versao_modulo_peticionamento.php

### ISSUE THREAD

**Issue by eduardosramos** [anatelgovbr/mod-sei-peticionamento#9]
Olá, Nei, tudo bem?

Estou em processo de instalação do módulo de petionamento no SEI v. 3.1.5 e ao rodar o passo 5 do README.md obtenho a seguinte informação:

[root@5a5703891204 sip]# /usr/bin/php -c /etc/php.ini /opt/sip/scripts/sip_atualizar_versao_modulo_peticionamento.php 

Descrio: Chave BancoSip/UsuarioScript no encontrada.

Mensagem:
Chave BancoSip/UsuarioScript no encontrada.

Trilha de Processamento:
#0 {main}

Trilha de Processamento Original:
\n0 {main}

Estou rodando a partir de um container. Tudo está, até este passo, rodando bem. Se puder me indicar um caminho fico muito grato. 

Eduardo

**Comment by evertramos** [comment]
Fala @eduardosramos!

Você está rodando essa rotina dentro do container? Parece que não está conseguindo ler as configurações iniciais do script:

https://github.com/anatelgovbr/mod-sei-peticionamento/blob/5d5ddd76ae6e46b088915359a66a97415fe56836/sip/scripts/sip_atualizar_versao_modulo_peticionamento.php#L2212

Os scripts dos demais módulos rodaram dentro desse container?

**Comment by eduardosramos** [comment]
Oi, @evertramos.

Seguindo rigorosamente o manual de instalação do módulo, que exige **versão 3.1.5** do SEI.

Sim, roda tudo dentro de um container. Quando eu executo:
 
/usr/bin/php -c /etc/php.ini /opt/sip/scripts/sip_atualizar_versao_modulo_peticionamento.php 2>&1 > atualizacao_peticionamento_sip.log &

Entendo que ele vai ler o php.ini (que tem o path_infra setado) e vai ser o Sip.php que vai, a partir dele, ler o ConfiguracaoSIP.php, pegar as credenciais e executar a atualização (criar as tabelas etc). Já mudei o path no sip_atualizar_versao_modulo_peticionamento.php e nada.

Usamos o wssei e está ok. Não foi da minha época, mas acredito que rodou dentro do container sem problemas.

Obrigado!

**Comment by eduardosramos** [comment]
Era preciso incluir as duas entradas novas no arquivo ConfiguracaoSip.php 

BancoSip
UsuarioScript
